# permissions for end users to edit examples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: example-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: my-k8s-operator
    app.kubernetes.io/part-of: my-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: example-editor-role
rules:
- apiGroups:
  - example.dev.montree.me
  resources:
  - examples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.dev.montree.me
  resources:
  - examples/status
  verbs:
  - get
